// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASFurp4zPiNqwfr74hTTxUgAbm065r64M',
    appId: '1:606673582480:web:b054e9b5d1c4b584a65b15',
    messagingSenderId: '606673582480',
    projectId: 'netflix-645cb',
    authDomain: 'netflix-645cb.firebaseapp.com',
    databaseURL: 'https://netflix-645cb-default-rtdb.firebaseio.com',
    storageBucket: 'netflix-645cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCku-VcmQu_YXT6N8hrsNyjQVYkMOs_r7w',
    appId: '1:606673582480:android:16ccba4b9d508a73a65b15',
    messagingSenderId: '606673582480',
    projectId: 'netflix-645cb',
    databaseURL: 'https://netflix-645cb-default-rtdb.firebaseio.com',
    storageBucket: 'netflix-645cb.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX4TC8iPJt6LVoi_BEsMiiKhrI4eGDGUU',
    appId: '1:606673582480:ios:e6eb1886b4134647a65b15',
    messagingSenderId: '606673582480',
    projectId: 'netflix-645cb',
    databaseURL: 'https://netflix-645cb-default-rtdb.firebaseio.com',
    storageBucket: 'netflix-645cb.appspot.com',
    iosBundleId: 'com.example.netflix.RunnerTests',
  );
}
